### ISSUE TITLE
Issue with NANs with the UGW method

### ISSUE THREAD

**Issue by npielawski** [6Ulm/UCOOT_code#1]
Hello,

thanks for sharing the code of your method. I am trying to use the UGW version on my data, and the notebook has been helpful to set things up. Unfortunately, all the combinations of parameters I tried gave me NaN issues. I saw some comment mentioning something about that so I set the rhos to infinity, but quickly I get NaNs again.

Here is an example:
`Cost at iteration 1: 551820.0
Cost at iteration 2: nan
Cost at iteration 3: nan
...`

Do you have any advices on parameters to set? My matrices are approximately 2000x2000 and 1000x1000, is that too big maybe?

Thanks in advance for your help.

Best,
Nicolas

**Comment by alexisthual** [comment]
Your matrices' sizes are more than acceptable I think!
Maybe normalizing these matrices could help (it usually does for me), as I guess the NaNs appear when the logsumexp blows up because of high values in the feature matrices.

**Comment by 6Ulm** [comment]
Hi @npielawski ,

Can you specify your choice of the hyper-parameters? If you have NaN, it is very likely because `uot_mode` is set to `"mm"`. This choice can be problematic when the magnitude of the data is large, which seems to be the your case, as far as I can see from your cost at the first iteration.

Roughly speaking, during the update of the algo `uot_mode = "mm"`, you will multiply the coupling with a matrix of the form $\exp^{- \text{magnitude of data}^2 / \text{sum of rho}}$. So if the magnitude is large and the rho are much smaller, this matrix is more or less zero matrix, meaning that the first iteration will result in zero matrix and the second iteration will result in NaN because you are dividing by zero matrix.

As @alexisthual suggests, it is usually a good idea to normalize the data (or at least control the magnitude) beforehand. Note that in optimal transport, the magnitude of the data matters as it will impact the choice of hyper-parameters and the quality of your training process (slow or fast convergence, good or bad performance/accuracy).

**Comment by npielawski** [comment]
Thanks for your replies!

@alexisthual was right: it was the matrices that needed to be normalized.

uot_mode was set to "mm" but then I saw the comment about possible NaNs so moved to "entropic".

**Comment by 6Ulm** [comment]
Please keep in mind that, while `uot_mode = "entropic"` should not suffer this magnitude issue because it is implemented in log domain, it is much slower per iteration than "mm". So I would recommend you to use "mm". But even if you consider to use "entropic", it is a good idea to normalize the data first.
